# Generated by Django 3.2.8 on 2021-11-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_venta',
            field=models.IntegerField(),
        ),
    ]
